export const SET_LOADING = 'SET_LOADING';
export const FETCH_BEVERAGES = 'FETCH_BEVERAGES';
export const SET_RELEASE_DATES = 'SET_RELEASE_DATES';
export const SET_SELECTED_RELEASE_DATE = 'SET_SELECTED_RELEASE_DATE';
export const SET_SEARCH_PHRASE = 'SET_SEARCH_PHRASE';
export const SET_MENU_ITEMS = 'SET_MENU_ITEMS';
export const FAILURE = 'FAILURE';
