name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install awscli
      run: sudo apt-get -y -qq install awscli

    - name: Enable Cloudfront CLI
      run: aws configure set preview.cloudfront true

    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm run lint
        npm run test:unit

    - name: Deploy to S3 and invalidate cache
      run: |
        aws s3 sync ./dist s3://systemnytt.se/ --acl public-read --region eu-north-1 --delete
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
